"""Convert ../sgi_logo/models/*.obj into models.js for polyhedra.html.

Keeps only closed, convex polyhedra with faces (skips *_frame wireframes),
drops geometric duplicates, and orients every face counter-clockwise when
seen from outside. Re-run after adding models:  python3 build_models.py
"""
import glob, json, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'sgi_logo', 'models')

NAMES = {
    'tet': 'Tetrahedron', 'cube': 'Cube', 'oct': 'Octahedron', 'dod': 'Dodecahedron',
    'ico': 'Icosahedron', 'tr_tet': 'Truncated tetrahedron', 'cubo': 'Cuboctahedron',
    'tr_cube': 'Truncated cube', 'tr_oct': 'Truncated octahedron',
    'rh_cubo': 'Rhombicuboctahedron', 'tr_cubo': 'Truncated cuboctahedron',
    'sn_cube': 'Snub cube', 'icosid': 'Icosidodecahedron', 'tr_dod': 'Truncated dodecahedron',
    'tr_ico': 'Truncated icosahedron', 'rh_icosid': 'Rhombicosidodecahedron',
    'tr_icosid': 'Truncated icosidodecahedron', 'sn_dod': 'Snub dodecahedron',
    'tri_tet': 'Triakis tetrahedron', 'rd': 'Rhombic dodecahedron',
    'tri_oct': 'Triakis octahedron', 'tetr_hex': 'Tetrakis hexahedron',
    'delt_icosit': 'Deltoidal icositetrahedron', 'trap_icosit': 'Deltoidal icositetrahedron',
    'disd_dod': 'Disdyakis dodecahedron', 'hex_oct': 'Disdyakis dodecahedron',
    'pen_icosit': 'Pentagonal icositetrahedron', 'rt': 'Rhombic triacontahedron',
    'tri_ico': 'Triakis icosahedron', 'pent_dod': 'Pentakis dodecahedron',
    'delt_hexac': 'Deltoidal hexecontahedron', 'trap_hexac': 'Deltoidal hexecontahedron',
    'disd_tri': 'Disdyakis triacontahedron', 'hex_ico': 'Disdyakis triacontahedron',
    'disdyakis_triacontahedron': 'Disdyakis triacontahedron',
    'pen_hexac': 'Pentagonal hexecontahedron', 'disd_hex': 'Tetrakis hexahedron',
}
ORDER = list(dict.fromkeys(NAMES))  # display order: Platonic, Archimedean, Catalan


def parse(path):
    V, F = [], []
    for line in open(path):
        t = line.split()
        if not t:
            continue
        if t[0] == 'v':
            V.append([float(x) for x in t[1:4]])
        elif t[0] == 'f':
            F.append([int(x.split('/')[0]) - 1 for x in t[1:]])
    return np.array(V), F


def check(V, F):
    """Return (ok, reason, oriented faces)."""
    if not F:
        return False, 'no faces', None
    used = sorted({i for f in F for i in f})
    edges = {}
    for f in F:
        for a, b in zip(f, f[1:] + f[:1]):
            edges[frozenset((a, b))] = edges.get(frozenset((a, b)), 0) + 1
    if any(c != 2 for c in edges.values()):
        return False, 'not closed', None
    if len(used) - len(edges) + len(F) != 2:
        return False, 'not genus 0', None
    c = V[used].mean(0)
    scale = np.abs(V[used] - c).max()
    out = []
    for f in F:
        P = V[f]
        n = np.zeros(3)
        for i in range(len(f)):  # Newell normal
            p, q = P[i], P[(i + 1) % len(f)]
            n += np.cross(p, q)
        n /= np.linalg.norm(n)
        d = n @ P.mean(0)
        if n @ c > d:  # points inward -> flip
            f, n, d = f[::-1], -n, -d
        if np.abs(P @ n - d).max() > 1e-3 * scale:
            return False, 'non-planar face', None
        if (V[used] @ n - d).max() > 1e-4 * scale:
            return False, 'not convex', None
        out.append(f)
    return True, '', out


def signature(V, F):
    used = sorted({i for f in F for i in f})
    P = V[used] - V[used].mean(0)
    P /= np.linalg.norm(P, axis=1).max()
    D = np.linalg.norm(P[:, None] - P[None], axis=2)
    return (len(used), tuple(sorted(len(f) for f in F)),
            tuple(np.round(np.sort(D.ravel()), 3)))


models, seen = [], {}
files = sorted(glob.glob(os.path.join(SRC, '*.obj')),
               key=lambda p: (ORDER.index(os.path.basename(p)[:-4])
                              if os.path.basename(p)[:-4] in ORDER else 999, p))
for path in files:
    key = os.path.basename(path)[:-4]
    V, F = parse(path)
    ok, why, F = check(V, F)
    if not ok:
        print(f'skip {key:28s} {why}')
        continue
    sig = signature(V, F)
    if sig in seen:
        print(f'skip {key:28s} duplicate of {seen[sig]}')
        continue
    seen[sig] = key
    used = sorted({i for f in F for i in f})
    remap = {o: n for n, o in enumerate(used)}
    P = V[used] - V[used].mean(0)
    P /= np.linalg.norm(P, axis=1).max()
    models.append({'id': key, 'name': NAMES.get(key, key),
                   'v': np.round(P, 6).tolist(),
                   'f': [[remap[i] for i in f] for f in F]})
    print(f'keep {key:28s} V={len(used):3d} F={len(F):3d}')

with open(os.path.join(HERE, 'models.js'), 'w') as fh:
    fh.write('// Generated by build_models.py from sgi_logo/models/*.obj; do not edit.\n')
    fh.write('window.POLYHEDRA = ' + json.dumps(models, separators=(',', ':')) + ';\n')
print(len(models), 'models written')
